export const ENDPOINTS = {
  GITHUB_LOGIN: "/api/v1/auth/login/github",
  EMAIL_LOGIN: "/api/v1/auth/login",
  EMAIL_REFRESH: "/api/v1/auth/refresh",
  EMAIL_AUTH: "/api/v1/auth/login/github",
  EMAIL_SIGNUP: "/api/v1/users/signup",
  GET_USER_NICKNAME: "/api/v1/users?keyword=",
  GET_USER_PROFILE: <T>(userId: T) => `/api/v1/users/${userId}`,
  PUT_USER_PROFILE: <T>(userId: T) => `/api/v1/users/${userId}`,
  PUT_USER_PASSWORD: <T>(userId: T) => `/api/v1/users/${userId}/password`,
  EMAIL_DOUBLE_CHECK: "/api/v1/users/email/check",
  NICKNAME_DOUBLE_CHECK: "/api/v1/users/nickname/check",
  GET_SKILLS: <T>(keyword: T) =>
    `/api/v1/skills${keyword ? `?keyword=${keyword}` : ""}`,
  UPLOAD_PROJECT_FILES: "/api/v1/projects/files",
  UPLOAD_PROJECT: "/api/v1/projects",
  PUT_PROJECT: <T>(projectId: T) => `/api/api/v1/projects/${projectId}`,
  DELETE_PROJECT: <T>(projectId: T) => `/api/api/v1/projects/${projectId}`,
  GET_PROJECT_DETAILS: <T>(projectId: T) => `/api/v1/projects/${projectId}`,
  GET_ALL_PROJECTS: "/api/v1/projects",
  UPLOAD_LIKE: "/api/v1/likes",
}
