name: deploy

on:
  pull_request:
    types: [opened, ready_for_review]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Cache node modules
        uses: actions/cache@v3
        id: npm-cache
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Dependencies
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: |
          echo 'npm cache existed'
          npm ci

      - name: lint
        run: npm run lint

      - name: build
        run: npm run build

      - name: If build fail
        if: ${{ failure() }}
        uses: actions/github-script@v6
        with:
          script: |
            const pull_number = ${{ github.event.pull_request.number }}
            await github.rest.pulls.createReview({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pull_number,
              body: '빌드에 실패했습니다. Commits 탭에서 에러를 확인하고 먼저 수정해주세요.',
            })

      - name: Assign assignee
        uses: hkusu/review-assign-action@v1
        with:
          assignees: ${{ github.actor }}

      - name: Assign reviewers randomly
        uses: ./.github/actions/reviewers
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          reviewers: ${{vars.reviewers}}
